---
abstract: 'Rudimentary profiling for Template Toolkit'
author:
  - 'Andy Lester'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-ShowStartStop
requires:
  Template::Context: 0
  Time::HiRes: 0
  parent: 0
version: 1.00
